### ISSUE TITLE
Very unclear comparison of effect sizes

### ISSUE THREAD

**Issue by lindseyberlin** [learn-co-curriculum/dsc-statistical-power#1]
This sentence is terrible and also wrong: "an unfair coin where  P(heads)=.6P(heads)=.6  for example, is not apt to lead to the reject of the null-hypothesis in the current formulation."
You're trying to say that the effect of Ha = .6 is different from Ha = .8 in some way (I think?) but honestly that paragraph is terrible - please stop using semi-colons.

**Comment by fpolchow** [comment]
Thank you for the feedback Lindsey :) I've added more clarification regarding the relationship between effect size and power as well as a link to a resource that provides a visual example demonstrating their relationship with one another.
