### ISSUE TITLE
Incorrect formulas in cells 2 and 3

### ISSUE THREAD

**Issue by ccsurratt** [learn-co-curriculum/dsc-statistical-power#4]
## Link to Canvas

https://learning.flatironschool.com/courses/6484/assignments/241640?module_item_id=568120

## Issue Subtype

- [X] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [X] Other (explain below)

## Describe the Issue
Error in the formulas for Cohen's d (cells 2 and 3)

### Source

```
# Cell 2
m1 = .55
m2 = .5
p = m2
rows = []
for n in [10, 20, 50, 500]:
    std = np.sqrt(n*p*(1-p))
    d = (m1-m2)/std
    rows.append({'Effect_Size': d, 'STD': std, 'Num_observations': n})
print('Hypothetical effect sizes for p(heads)=.55 vs p(heads)=.5')
pd.DataFrame(rows)

# Cell 3
m2 = .5
rows = {}
for n in [10, 20, 50, 500]:
    temp_dict = {}
    for m1 in [.51, .55, .6, .65, .7, .75, .8, .85, .9]:
        p = m1
        std = np.sqrt(n*p*(1-p))
        d = (m1-m2)/std
        temp_dict[m1] = d
    rows[n] = temp_dict
print('Hypothetical effect sizes for various alternative hypotheses')
df = pd.DataFrame.from_dict(rows, orient='index')
# df.index = [10,20,50, 500]
# df.index.name = 'Sample_Size'
# df.columns.name = 'Alternative Hypothesis'
df


```

### Concern

The mean of a binomial distribution is not the probability, it is the expected value. (i.e. m = n*p)

This is undermining the key concept in this lesson, as the effect size is decreasing rather than increasing as the sample size increases.

Additionally, the standard deviations used in cells 2 and cells 3 do not match. Cell 2 uses the standard deviation of the null hypothesis (p = 0.5), while cell 3 uses the standard deviation of the alternative hypothesis (varying values for p). In the proposed solution below, I have used p=0.5 for both standard deviations, as we should be comparing the observed (unfair) coin to the null hypothesis that the coin is fair. 

## (Optional) Proposed Solution

```
# Cell 2
p1 = .55
p2 = .5
rows = []
for n in [10, 20, 50, 500]:
    m1 = p1*n
    m2 = p2*n
    std = np.sqrt(n*p2*(1-p2))
    d = (m1-m2)/std
    rows.append({'Effect_Size': d, 'STD': std, 'Num_observations': n})
print('Hypothetical effect sizes for p(heads)=.55 vs p(heads)=.5')
pd.DataFrame(rows)

# Cell 3
p2 = .5
rows = {}
for n in [10, 20, 50, 500]:
    temp_dict = {}
    for p1 in [.51, .55, .6, .65, .7, .75, .8, .85, .9]:
        m1 = p1*n
        m2 = p2*n
        std = np.sqrt(n*p2*(1-p2))
        d = (m1-m2)/std
        temp_dict[p1] = d
    rows[n] = temp_dict
print('Hypothetical effect sizes for various alternative hypotheses')
df = pd.DataFrame.from_dict(rows, orient='index')
# df.index = [10,20,50, 500]
# df.index.name = 'Sample_Size'
# df.columns.name = 'Alternative Hypothesis'
df
```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [X] Saturn Cloud from Canvas

## Any Additional Context?

These changes significantly affect the effect size output. Markdown will need to be revised.

**Comment by bpurdy-ds** [comment]
A very perspicuous comment. You are correct on all accounts. Fixing now.
